src/Imv/CoreBundle/Entity/Word.php
<?php

namespace Imv\CoreBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Word
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Imv\CoreBundle\Entity\WordRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Word implements EntityInterface
{
    use Timestampable;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="details", type="string", length=255)
     */
    private $details;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\OneToMany(targetEntity="Imv\CoreBundle\Entity\Translation", mappedBy="word", cascade={"persist", "remove"})
     */
    private $translations;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="Imv\CoreBundle\Entity\WordList", mappedBy="words", cascade={"persist"})
     */
    private $wordlists;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->wordlists = new ArrayCollection();
        $this->translations = new ArrayCollection();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getUrlParams()
    {
        return array('id' => $this->getId());
    }

    /**
     * Set details
     *
     * @param string $details
     *
     * @return Word
     */
    public function setDetails($details)
    {
        $this->details = $details;
        return $this;
    }

    /**
     * Get details
     *
     * @return string 
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Add a translation
     *
     * @param Translation $translation
     * @param boolean $cascade
     *
     * @return Word
     */
    public function addTranslation(Translation $translation, $cascade=true)
    {
        $this->translations[] = $translation;
        if ($cascade) {
            $translation->setWord($this, false);
        }
        return $this;
    }

    /**
     * Remove a translation
     *
     * @param Translation $translation
     * @param boolean $cascade
     *
     * @return Word
     */
    public function removeTranslation(Translation $translation, $cascade=true)
    {
        $this->translations->removeElement($translation);
        if ($cascade) {
            $translation->removeWord(false);
        }
    }

    /**
     * Get translations
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTranslations()
    {
        return $this->translations;
    }

    /**
     * Get the translation for a given locale
     *
     * @param Locale $locale
     *
     * @return Translation
     */
    public function getTranslation(Locale $locale)
    {
        foreach ($this->translations as $translation) {
            if ($translation->getLocale() == $locale) {
                return $translation;
            }
        }
    }

    /**
     * Add wordList
     *
     * @param WordList $wordlist
     * @param boolean $cascade
     */
    public function addWordList(WordList $wordlist, $cascade=true)
    {
        $this->wordlists[] = $wordlist;
        if ($cascade) {
            $wordlist->addWord($this, false);
        }
    }

    /**
     * Remove wordlist
     *
     * @param WordList $wordlist
     * @param boolean $cascade
     */
    public function removeWordList(WordList $wordlist, $cascade=true)
    {
        $this->wordlists->removeElement($wordlist);
        if ($cascade) {
            $wordlist->removeWord($this, false);
        }
    }

    /**
     * Get wordlists
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getWordLists()
    {
        return $this->wordlists;
    }

    /**
     * Do stuff when a word is removed
     *
     * @ORM\PreRemove
     */
    public function onPreRemove()
    {
        foreach($this->wordlists as $wordlist) {
            $this->removeWordList($wordlist);
        }
    }
}

src/Imv/CoreBundle/Form/WordType.php
<?php

namespace Imv\CoreBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class WordType extends AbstractType
{
    /**
     * {@inheritDoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('details')
            ->add('wordlists', 'entity', array(
                'multiple'  => true,
                'expanded' => true,
                'property' => 'name',
                'class'  => 'Imv\CoreBundle\Entity\WordList',
                'by_reference' => false
            ))
            ->add('translations', 'collection', array(
                'type' => new TranslationType(),
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false
            ))
        ;
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Imv\CoreBundle\Entity\Word',
            'cascade_validation' => true
        ));
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {
        return 'imv_corebundle_word';
    }
}

src/Imv/CoreBundle/Controller/WordController.php
<?php

namespace Imv\CoreBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Imv\CoreBundle\Entity\Word;
use Imv\CoreBundle\Form\WordType;

/**
 * Word controller.
 *
 * @Route("/word")
 */
class WordController extends EntityController
{
    /**
     * @inheritdoc
     */
    protected function getRepositoryName()
    {
        return 'ImvCoreBundle:Word';
    }

    /**
     * @inheritdoc
     */
    protected function getRouteNamePrefix()
    {
        return 'imv_word';
    }

    /**
     * @inheritdoc
     */
    protected function getFormType()
    {
        return new WordType();
    }

    /**
     * Create a new Word entity.
     *
     * @Route("/", name="imv_word_create")
     * @Method("POST")
     * @Template("ImvCoreBundle:Word:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $entity = new Word();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('imv_word_show', $entity->getUrlParams()));
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Display a form to create a new Word entity.
     *
     * If a WordList is present, the new word will be automatically
     * added to the wordlist
     *
     * @Route("/new", name="imv_word_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction(Request $request)
    {
        $entity = new Word();

        $wordlist_id = (int)$request->get('wordlist', null);
        if (null !== $wordlist_id) {
            $wordlist = $this->getManager()->getRepository('ImvCoreBundle:WordList')->find($wordlist_id);
            $entity->addWordList($wordlist);
        }

        $form   = $this->createCreateForm($entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Find and display a Word entity.
     *
     * @Route("/{id}", requirements={"id": "\d+"}, name="imv_word_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction(Word $entity)
    {
        $deleteForm = $this->createDeleteForm($entity);

        return array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Display a form to edit an existing Word entity.
     *
     * @Route("/{id}/edit", requirements={"id" = "\d+"}, name="imv_word_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction(Word $entity)
    {
        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($entity);

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Edit an existing Word entity.
     *
     * @Route("/{id}", requirements={"id" = "\d+"}, name="imv_word_update")
     * @Method("PUT")
     * @Template("ImvCoreBundle:Word:edit.html.twig")
     */
    public function updateAction(Request $request, Word $entity)
    {
        $deleteForm = $this->createDeleteForm($entity);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $this->getManager()->flush();

            return $this->redirect($this->generateUrl('imv_word_edit', $entity->getUrlParams()));
        }

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Delete a Word entity.
     *
     * @Route("/{id}", requirements={"id" = "\d+"}, name="imv_word_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, Word $entity)
    {
        $form = $this->createDeleteForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getManager();
            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('imv_wordlist'));
    }
}

src/Imv/CoreBundle/Resources/views/Word/edit.html.twig
{% extends '::base.html.twig' %}

{% block title %}{{ 'title.word.edit'|trans }}{% endblock %}

{% block body -%}
    <div class="page-header">
        <h1>{{ 'title.word.edit'|trans }}</h1>
    </div>

    {{ form_start(edit_form) }}
        {{ form_errors(edit_form) }}

        {{ form_row(edit_form.details, {'label': 'field.word.details'|trans}) }}

        <ul class="translations" data-prototype="{{ form_widget(edit_form.translations.vars.prototype)|e }}">
            {% for translation in edit_form.translations %}
                <li>
                    <div>
                        {{ form_row(translation) }}
                    </div>
                </li>
            {% endfor %}
        </ul>

        {{ form_rest(edit_form) }}
    {{ form_end(edit_form) }}

    {{ form_start(delete_form) }}
        {{ form_errors(delete_form) }}

        {{ form_row(delete_form.submit, {'attr': {'class': 'btn-danger btn-delete'}}) }}
    {{ form_end(delete_form) }}
{% endblock %}

{% block javascripts %}
<script defer="true">
    var collectionHolder = $('ul.translations');
    var addTranslationLink = $('<a href="#" class="add_translation_link">{{ 'action.translation.add'|trans }}</a>');
    var newLinkLi = $('<li></li>').append(addTranslationLink);

    jQuery(document).ready(function() {
        collectionHolder.find('li').each(function() {
            Imv.addCollectionFormDeleteLink($(this));
        });
        collectionHolder.append(newLinkLi);
        addTranslationLink.on('click', function(e) {
            // Prevent the browser to add a « # » in the URL
            e.preventDefault();
            Imv.addCollectionForm(collectionHolder, newLinkLi);
        });
    });
</script>
{% endblock %}

src/Imv/CoreBundle/Resources/views/Word/new.html.twig
{% extends '::base.html.twig' %}

{% block title %}{{ 'title.word.new'|trans }}{% endblock %}

{% block body -%}
    <div class="page-header">
        <h1>{{ 'title.word.new'|trans }}</h1>
    </div>

    {{ form_start(form) }}
        {{ form_errors(form) }}

        {{ form_row(form.details, {'label': 'field.word.details'|trans}) }}

        {{ form_rest(form) }}
    {{ form_end(form) }}

    <ul class="record_actions">
    </ul>
{% endblock %}

src/Imv/CoreBundle/Resources/views/Word/show.html.twig
{% extends '::base.html.twig' %}

{% block title %}{{ 'title.word.show'|trans }}{% endblock %}

{% set _format_datetime = 'format.datetime'|trans %}

{% set wordlist_links %}
    {% for wl in entity.getWordLists() %}
        <a href="{{ path('imv_wordlist_show', wl.urlParams) }}">{{ wl.name }}</a>{% if not loop.last %}, {% endif %}
    {% endfor %}
{% endset %}

{% block body -%}
    <div class="page-header">
        <h1>{{ 'title.word.show'|trans }}</h1>
    </div>

    <p>
        {% filter replace({'%text%': wordlist_links|trim})|raw %}
            {{ 'content.word.associated.wordlist'|transchoice(entity.wordlists.count) }}
        {% endfilter %}
    </p>

    <table class="record_properties">
        <tbody>
            <tr>
                <th>{{ 'field.entity.id'|trans }}</th>
                <td>{{ entity.id }}</td>
            </tr>
            <tr>
                <th>{{ 'field.entity.createdAt'|trans }}</th>
                <td>{{ entity.createdAt|date(_format_datetime) }}</td>
            </tr>
            <tr>
                <th>{{ 'field.word.details'|trans }}</th>
                <td>{{ entity.details }}</td>
            </tr>
            <tr>
                <th>{{ 'field.entity.updatedAt'|trans }}</th>
                <td>{{ entity.updatedAt|date(_format_datetime) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="row form-group">
        <div class="col-sm-offset-2 col-sm-10 ">
            <a class="btn btn-primary btn-edit" href="{{ path('imv_word_edit', entity.urlParams) }}">
                {{ 'action.entity.edit'|trans }}
            </a>
        </div>
    </div>

    {{ form_start(delete_form) }}
        {{ form_errors(delete_form) }}

        {{ form_row(delete_form.submit, {'attr': {'class': 'btn-danger btn-delete'}}) }}
    {{ form_end(delete_form) }}


{% endblock %}